#!/usr/bin/env python3
# ─────────────────────────────────────────────────────────────────────────────
# Star Alliance — INSTALL AGENTS  (costume → crew)
#
# THE PROBLEM: agents are written as source-of-truth definitions in `agents/`,
# but Hermes profiles live under `~/.hermes/profiles/star-alliance-<agent>/`.
# The profile AGENTS.md files are GENERATED from the source — never hand-edit
# them, or the next run overwrites the edit.
#
# THE FIX (safe + additive): generate one Hermes profile AGENTS.md per agent
# from its source file in `agents/`.
#   1. ~/.hermes/profiles/star-alliance-<agent>/AGENTS.md  — Hermes profile personas
#
# The Hermes AGENTS.md carries a header noting it is auto-generated from the
# source-of-truth agent file. Edit the source, run install_agents.py.
#
#   python3 guild/install_agents.py            # write all
#   python3 guild/install_agents.py --check    # report drift, write nothing
# ─────────────────────────────────────────────────────────────────────────────
import os, sys, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "agents"
HERMES_HOME = pathlib.Path(os.environ.get("HERMES_HOME", pathlib.Path.home() / ".hermes"))
DST_HERMES = HERMES_HOME / "profiles"

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", re.S)


def parse(path):
    txt = open(path, encoding="utf-8").read()
    m = FM_RE.match(txt)
    if not m:
        return None, None, None
    fm, body = m.group(1), m.group(2)
    fields = {}
    for line in fm.splitlines():
        mm = re.match(r"([A-Za-z_][\w-]*)\s*:\s*(.*)$", line)
        if mm:
            fields[mm.group(1)] = mm.group(2).strip()
    return fields, body, txt


def hermes_agents_text(agent_name, fields, body):
    """Hermes profile AGENTS.md format — keeps the full persona body, with a
    header noting this is auto-generated."""
    header = f"""# {agent_name} — Star Alliance Agent Profile (Hermes)

> **Auto-generated** from `agents/{agent_name}.md` (source of truth).
> Edit the source file, then run `python3 guild/install_agents.py` to regenerate.
> Do NOT edit this file directly — it will be overwritten.

---

"""
    return header + body.strip() + "\n"


def write_hermes(fields, text, check):
    """Write to ~/.hermes/profiles/star-alliance-<agent>/AGENTS.md."""
    name = fields["name"]  # e.g. "the-architect"
    profile_name = f"star-alliance-{name.replace('the-', '')}"
    profile_dir = DST_HERMES / profile_name
    agents_path = profile_dir / "AGENTS.md"

    # Extract the body for the hermes format
    body_match = re.search(r"---\n.*?\n---\n(.*)", text, re.DOTALL)
    body = body_match.group(1) if body_match else ""
    hermes_content = hermes_agents_text(name, fields, body)

    if not profile_dir.exists():
        return 1, f"  SKIP {profile_name} (profile dir missing — run: hermes profile create {profile_name})"

    cur = agents_path.read_text(encoding="utf-8") if agents_path.exists() else None
    if cur == hermes_content:
        return 0, f"  ok    {profile_name} (hermes)"
    if check:
        return 1, f"  DRIFT {profile_name} (hermes — would update)"
    agents_path.write_text(hermes_content, encoding="utf-8")
    return 1, f"  wrote {profile_name} (hermes)"


def main():
    check = "--check" in sys.argv

    agents = sorted(SRC.glob("the-*.md"))
    if not agents:
        print("no agent files found in agents/", file=sys.stderr)
        return 1

    drift = 0
    for path in agents:
        fields, body, _ = parse(path)
        if not fields or "name" not in fields:
            print(f"  skip (no name): {path.name}", file=sys.stderr)
            continue

        # Personas (e.g. the Butler — the voice you talk to) run as the active
        # session model, NOT as a spawnable subagent. They get NO profile
        # AGENTS.md generated. Remove any stale one.
        if str(fields.get("type", "")).strip().lower() == "persona":
            if check:
                print(f"  persona {fields['name']} (no profile file — correct)")
            else:
                print(f"  persona {fields['name']} (no profile file — correct)")
            continue

        # Build a synthetic text with frontmatter for body extraction
        text = path.read_text(encoding="utf-8")
        d, msg = write_hermes(fields, text, check)
        print(msg)
        drift += d

    if check and drift:
        print(f"\n{drift} drift(s) detected — run without --check to install")
        return 1
    print(f"\n{len(agents)} agents processed ({'check' if check else 'installed'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())