#!/usr/bin/env python3
# ─────────────────────────────────────────────────────────────────────────────
# Star Alliance — INSTALL AGENTS  (costume → crew)
#
# THE PROBLEM (audit Wave D): the members are written as Claude Code agent
# definitions, and high-alert.py already fires the ⚔ "Member reports for duty"
# klaxon when a tool dispatches a sub-agent whose type is a guild member — but
# there is no  .claude/agents/  directory, so `subagent_type: the-developer`
# resolves to nothing. The whole roster therefore runs as PERSONAS the Butler
# role-plays inline in one context: no real parallelism, no context isolation,
# no independent doer fan-out. The guild is a costume.
#
# THE FIX (safe + additive): generate one real agent file per member into
# BOTH destinations:
#   1. .claude/agents/<name>.md  — Claude Code agent files (legacy)
#   2. ~/.hermes/profiles/star-alliance-<member>/AGENTS.md  — Hermes profile personas
#
# The hermes AGENTS.md carries a header noting it is auto-generated from the
# source-of-truth member file. Edit the source, run install_agents.py.
#
#   python3 guild/install_agents.py            # write both
#   python3 guild/install_agents.py --check    # report drift, write nothing
#   python3 guild/install_agents.py --hermes-only  # only write hermes profiles
#   python3 guild/install_agents.py --claude-only  # only write .claude/agents
# ─────────────────────────────────────────────────────────────────────────────
import os, sys, re, glob, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "star-alliance-members"
DST_CLAUDE = ROOT / ".claude" / "agents"
HERMES_HOME = pathlib.Path(os.environ.get("HERMES_HOME", pathlib.Path.home() / ".hermes"))
DST_HERMES = HERMES_HOME / "profiles"

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", re.S)
# keep only the keys the Claude agent loader expects
KEEP = ("name", "description", "model", "tools")


def parse(path):
    txt = open(path, encoding="utf-8").read()
    m = FM_RE.match(txt)
    if not m:
        return None, None, None
    fm, body = m.group(1), m.group(2)
    fields = {}
    for line in fm.splitlines():
        mm = re.match(r"([A-Za-z_][\w-]*)\s*:\s*(.*)$", line)
        if mm:
            fields[mm.group(1)] = mm.group(2).strip()
    return fields, body, txt


def agent_text(fields, body):
    """Claude Code agent file format."""
    out = ["---"]
    for k in KEEP:
        if k in fields and fields[k]:
            out.append(f"{k}: {fields[k]}")
    out.append("---")
    out.append("")
    out.append(body.strip())
    out.append("")
    return "\n".join(out)


def hermes_agents_text(member_name, fields, body):
    """Hermes profile AGENTS.md format — keeps the full persona body, with a
    header noting this is auto-generated."""
    header = f"""# {member_name} — Star Alliance Member Profile (Hermes)

> **Auto-generated** from `star-alliance-members/{member_name}.md` (source of truth).
> Edit the source file, then run `python3 guild/install_agents.py` to regenerate.
> Do NOT edit this file directly — it will be overwritten.

---

"""
    return header + body.strip() + "\n"


def write_claude(fields, text, check):
    """Write to .claude/agents/<name>.md. Returns (drift, status_msg)."""
    dst = DST_CLAUDE / (fields["name"] + ".md")
    cur = dst.read_text(encoding="utf-8") if dst.exists() else None
    if cur == text:
        return 0, f"  ok    {fields['name']} (.claude)"
    if check:
        return 1, f"  DRIFT {fields['name']} (.claude — would update)"
    DST_CLAUDE.mkdir(parents=True, exist_ok=True)
    dst.write_text(text, encoding="utf-8")
    return 1, f"  wrote {fields['name']} (.claude)"


def write_hermes(fields, text, check):
    """Write to ~/.hermes/profiles/star-alliance-<member>/AGENTS.md."""
    name = fields["name"]  # e.g. "the-architect"
    profile_name = f"star-alliance-{name.replace('the-', '')}"
    profile_dir = DST_HERMES / profile_name
    agents_path = profile_dir / "AGENTS.md"

    hermes_text = hermes_agents_text(name, fields, text.split("---\n\n", 2)[-1] if "---\n\n" in text else "")

    # Also need to extract the body for the hermes format
    body_match = re.search(r"---\n.*?\n---\n(.*)", text, re.DOTALL)
    body = body_match.group(1) if body_match else ""
    hermes_content = hermes_agents_text(name, fields, body)

    if not profile_dir.exists():
        return 1, f"  SKIP {profile_name} (profile dir missing — run: hermes profile create {profile_name})"

    cur = agents_path.read_text(encoding="utf-8") if agents_path.exists() else None
    if cur == hermes_content:
        return 0, f"  ok    {profile_name} (hermes)"
    if check:
        return 1, f"  DRIFT {profile_name} (hermes — would update)"
    agents_path.write_text(hermes_content, encoding="utf-8")
    return 1, f"  wrote {profile_name} (hermes)"


def main():
    check = "--check" in sys.argv
    hermes_only = "--hermes-only" in sys.argv
    claude_only = "--claude-only" in sys.argv

    members = sorted(SRC.glob("the-*.md"))
    if not members:
        print("no member files found", file=sys.stderr)
        return 1

    drift = 0
    for path in members:
        fields, body, _ = parse(path)
        if not fields or "name" not in fields:
            print(f"  skip (no name): {path.name}", file=sys.stderr)
            continue

        # Personas (e.g. the Butler — the voice you talk to) run as the active
        # session model, NOT as a spawnable subagent. They get NO agent file
        # in either destination. Remove any stale one.
        if str(fields.get("type", "")).strip().lower() == "persona":
            if not hermes_only:
                stale = DST_CLAUDE / (fields["name"] + ".md")
                if stale.exists():
                    if check:
                        print(f"  DRIFT {fields['name']} (persona — stale agent file present)")
                        drift += 1
                    else:
                        stale.unlink()
                        print(f"  removed {fields['name']} (persona — no agent file)")
                else:
                    print(f"  persona {fields['name']} (no agent file — correct)")
            continue

        text = agent_text(fields, body)

        # Write to .claude/agents/
        if not hermes_only:
            d, msg = write_claude(fields, text, check)
            print(msg)
            drift += d

        # Write to ~/.hermes/profiles/star-alliance-*/AGENTS.md
        if not claude_only:
            d, msg = write_hermes(fields, text, check)
            print(msg)
            drift += d

    if check and drift:
        print(f"\n{drift} drift(s) detected — run without --check to install")
        return 1
    print(f"\n{len(members)} members processed ({'check' if check else 'installed'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())